# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Crawler-Period-Mode

on:
  push:
  schedule:
    - cron: "0 0 * * *"
    - cron: "15 0 * * *"
    - cron: "30 0 * * *"
    - cron: "45 0 * * *"
    - cron: "0 1 * * *"
    - cron: "15 1 * * *"
    - cron: "30 1 * * *"
    - cron: "45 1 * * *"
    - cron: "0 2 * * *"
    - cron: "15 2 * * *"
    - cron: "30 2 * * *"
    - cron: "45 2 * * *"
    - cron: "0 3 * * *"
    - cron: "15 3 * * *"
    - cron: "30 3 * * *"
    - cron: "45 3 * * *"
    - cron: "0 4 * * *"
    - cron: "15 4 * * *"
    - cron: "30 4 * * *"
    - cron: "45 4 * * *"
    - cron: "0 5 * * *"
    - cron: "15 5 * * *"
    - cron: "30 5 * * *"
    - cron: "45 5 * * *"
    - cron: "0 6 * * *"
    - cron: "15 6 * * *"
    - cron: "30 6 * * *"
    - cron: "45 5 * * *"
    - cron: "0 7 * * *"
    - cron: "15 7 * * *"
    - cron: "30 7 * * *"
    - cron: "45 7 * * *"
    - cron: "0 8 * * *"
    - cron: "15 8 * * *"
    - cron: "30 8 * * *"
    - cron: "45 8 * * *"
    - cron: "0 9 * * *"
    - cron: "30 9 * * *"
    - cron: "0 10 * * *"
    - cron: "30 10 * * *"
    - cron: "0 11 * * *"
    - cron: "30 12 * * *"
    - cron: "45 19 * * *"
    - cron: "00 20 * * *"
    - cron: "15 20 * * *"
    - cron: "30 20 * * *"
    - cron: "45 20 * * *"
    - cron: "00 21 * * *"
    - cron: "15 21 * * *"
    - cron: "30 21 * * *"
    - cron: "45 21 * * *"
    - cron: "00 22 * * *"
    - cron: "15 22 * * *"
    - cron: "30 22 * * *"
    - cron: "45 22 * * *"
    - cron: "00 23 * * *"
    - cron: "15 23 * * *"
    - cron: "30 23 * * *"
    - cron: "45 23 * * *"
    
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions (For Debug)'
        required: false
        default: 'false'
      period:
        description: 'Search Period'
        required: true
        default: '1'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Start Crawling & Barking
        run: |
          python main.py --action --period=${{github.event.inputs.period}}

#      - name: Delete workflow runs
#        uses: GitRML/delete-workflow-runs@main
#        with:
#          token: ${{ secrets.AUTH_PAT }}
#          repository: ${{ github.repository }}
#          retain_days: 10
